# Generated by Django 4.2.4 on 2023-10-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_shippingaddress_forwarder_shippingaddress_is_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='is_office',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='office',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
