# Generated by Django 4.2.4 on 2023-10-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_shippingaddress_is_office_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='comments',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
