# Generated by Django 4.2.4 on 2023-10-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_shippingaddress_comments_shippingaddress_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('titleBg', models.CharField(blank=True, max_length=50, null=True)),
                ('titleEn', models.CharField(blank=True, max_length=50, null=True)),
                ('htmlBg', models.TextField(blank=True, null=True)),
                ('htmlEn', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='comments',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
