# Generated by Django 4.2.4 on 2023-10-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_footerterms_alter_shippingaddress_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footerterms',
            old_name='key',
            new_name='mainKey',
        ),
    ]
