products = [
    {
        '_id': "1",
        'name': "Тялото говори",
        'image': "/images/body-talks-korica.jpg",
        'description': "„Тялото говори“ (Изчерпана. Отделни бройки с наранена външност)",
        'brand': "Tsveta Book",
        'category': "Books",
        'price': 9.99,
        'countInStock': 0,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        '_id': "2",
        'name': "„Аз искам да бъда…“ (сборно издание), твърда корица",
        'image': "/images/koriza_lize_az_iskam.jpg",
        'description': "„Аз искам да бъда…“ (сборно издание), твърда корица, (корична цена 16,90 лв.)",
        'brand': "Tsveta Book",
        'category': "Books",
        'price': 16.9,
        'countInStock': 7,
        'rating': 4.0,
        'numReviews': 8,
    },
    {
        '_id': "3",
        'name': "„Аз искам да бъда…“ (сборно издание), мека корица",
        'image': "/images/koriza_lize_az_iskam.jpg",
        'description': "„Аз искам да бъда…“ (сборно издание), мека корица, корична цена 12,90 лв.",
        'brand': "Tsveta Book",
        'category': "Books",
        'price': 12.9,
        'countInStock': 5,
        'rating': 3,
        'numReviews': 12,
    },
    {
        '_id': "4",
        'name': "„Книга 1 Инспектор Бу в разследване на кой се опита да отрови капитан Пърси“, мека корица",
        'image': "/images/inspectorbu1koriza.jpg",
        'description':
            "„Книга 1 Инспектор Бу в разследване на кой се опита да отрови капитан Пърси“, мека корица, корична цена 15,00 лв.",
        'brand': "Tsveta Book",
        'category': "Books",
        'price': 15.0,
        'countInStock': 11,
        'rating': 5,
        'numReviews': 12,
    },
    {
        '_id': "5",
        'name': "Книга 2, „Ягодовите кошмари на инспектор Бу“, мека корица",
        'image': "/images/zape4atkorizabujagodi2.jpg",
        'description': "Книга 2, „Ягодовите кошмари на инспектор Бу“, мека корица, корична цена 15,00 лв.",
        'brand': "Tsveta Book",
        'category': "Books",
        'price': 15.0,
        'countInStock': 7,
        'rating': 3.5,
        'numReviews': 10,
    },
    {
        '_id': "6",
        'name': "Книга 3, „Марли и Кари в „Свърталището“, мека корица",
        'image': "/images/korizamarliikari.jpg",
        'description': "Книга 3, „Марли и Кари в „Свърталището“, мека корица, корична цена 15,00 лв.",
        'brand': "Tsveta Book",
        'category': "Books",
        'price': 15.0,
        'countInStock': 9,
        'rating': 4,
        'numReviews': 12,
    },
]
